username = 'your username'
cid = 'your cid'
secret = 'your secret id'
redirect_uri = 'the uri you want to rediretc to '
uriPlaylist='uri of the playlist to update'
idPlaylist='id of the playlist to update'